config/routes.rb
BarcodeScanner::Application.routes.draw do
  mount Judge::Engine => '/judge'
  devise_for :users
  resources :locations

  resources :customers

  resources :tapes do
    resources :history, controller: 'history'
    collection { post :import }
    collection { get  :deleted }
  end

  resources :customers do
    resources :history, controller: 'audits'
    collection { post :import }
    collection { get  :deleted }
  end

  resources :consignments do
    collection do
      get 'checktape'
    end
  end

  root 'tapes#index'

end

app/models/tape.rb
class Tape < ActiveRecord::Base
	require 'csv'
	require 'roo'

	belongs_to :customer
	has_many :movements
	has_many :locations, :through => :consignments, :source => :to_location
	has_many :contents, :foreign_key => :tape_id
	has_many :consignments, :through => :contents

	acts_as_paranoid
	auditable
	#def location
	#	Consignment.where('tape_id = ?', id).order(date: :desc).first.to_location
	#end

	def location
		if self.consignments.count !=0
			if self.consignments.order(updated_at: :desc).first.in_transit == true
				Location.find_by_location('In Transit')
			else
				self.consignments.order(updated_at: :desc).first.to_location
			end
		else
			Location.find_by_location('Unassigned')
		end
	end

	def self.import(file)
	  spreadsheet = open_spreadsheet(file)
	  header = spreadsheet.row(1)
	  (2..spreadsheet.last_row).each do |i|
	    row = Hash[[header, spreadsheet.row(i)].transpose]
	    tape = find_by_reference(row["reference"]) || new
	    tape.attributes = row.to_hash
			logger.debug "#{tape.attributes}"
	    tape.save
	  end
	end

	def self.open_spreadsheet(file)
	  case File.extname(file.original_filename)
			when ".csv" then Roo::Csv.new(file.path)
		  when ".xls" then Roo::Excel.new(file.path)
		  when ".xlsx" then Roo::Excelx.new(file.path)
		else raise "Unknown file type: #{file.original_filename}"
	  end
	end

	def self.search(search)
	  if search
	    where('reference LIKE ?', "%#{search}%")
	  else
	    self.all
	  end
	end
end

app/controllers/tapes_controller.rb
class TapesController < ApplicationController
  before_action :set_tape, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token
  skip_before_filter :verify_authenticity_token

  # GET /tapes
  # GET /tapes.json
  def index
  #  @tapes = Tape.all
      @tapes = Tape.search(params[:search]).paginate(:per_page => 10, :page => params[:page])
  end

  # GET /tapes/1
  # GET /tapes/1.json
  def show
  end

  # GET /tapes/new
  def new
    @tape = Tape.new
    @customers = Customer.all
  end

  # GET /tapes/1/edit
  def edit
    @customers = Customer.all
    @locations = Location.all
  end

  # POST /tapes
  # POST /tapes.json
  def create
    Rails.logger = Logger.new(STDOUT)
    Rails.logger.debug tape_params.inspect
    #@tape = Tape.new(tape_params)

    #!!TODO!! Improve this block of code
    if params["tape"]["reference"].is_a?(Array) || params["tape"]["reference"].is_a?(Hash)
      params["tape"]["reference"].each do |reference|
        unless reference == ''
          @tape = Tape.new(:reference => reference, :customer_id => tape_params['customer_id'])
          @tape.save
        end
      end
    else
      unless params["tape"]["reference"] == ''
        @tape = Tape.new(:reference => params["tape"]["reference"], :customer_id => tape_params['customer_id'])
        @tape.save
      end
    end

    respond_to do |format|
      if @tape.save
        format.html { redirect_to tapes_path, success: "Tape Successfully Added!" }
        format.json { render action: 'show', status: :created, location: @tape }
      else
        format.html { render action: 'new' }
        format.json { render json: @tape.errors, status: :unprocessable_entity }
      end
    end

    #@location = Location.all
    #@customer = Customer.all

    #location_match = consignment_validation(params["tapes"])

    #@consignment.errors

    #!!TODO!! Figure out a way to write this better. Not Dry.
    #respond_to do |format|
    #  if location_match != false
    #    if @consignment.save
    #      format.html { redirect_to consignments_path, success: "Consignment Successfully Created!" }
    #      format.json { render action: 'show', status: :created, location: @consignment }
    #    else
    #      format.html { render action: 'new' }
    #      format.json { render json: @consignment.errors, status: :unprocessable_entity }
    #    end
    #  else
    #    format.html { render action: 'new' }
    #    format.json { render json: @consignment.errors, status: :unprocessable_entity }
    #  end
    #end





    #@tape = Tape.new(tape_params)

    #respond_to do |format|
    #  if @tape.save
    #    format.html { redirect_to @tape, notice: 'Tape was successfully created.' }
    #    format.json { render action: 'show', status: :created, location: @tape }
    #  else
    #    format.html { render action: 'new' }
    #    format.json { render json: @tape.errors, status: :unprocessable_entity }
    #  end
    #end
  end

  # PATCH/PUT /tapes/1
  # PATCH/PUT /tapes/1.json
  def update

    @consignment = Consignment.new(
      :from_location_id => Tape.find_by_id(params[:id]).location.id,
      :to_location_id => params[:tape][:location],
      :in_transit => false
    )
    @consignment.save

    @content = Content.new(
      :tape_id => params[:id],
      :consignment_id => @consignment.id,
    )
    @content.save

    respond_to do |format|
      if @tape.update(tape_params)
        format.html { redirect_to @tape, notice: 'Tape was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @tape.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tapes/1
  # DELETE /tapes/1.json
  def destroy
    @tape.deleted_by = current_user.email
    @tape.save
    @tape.destroy
    respond_to do |format|
      format.html { redirect_to tapes_url }
      format.json { head :no_content }
    end
  end

  def import
    Tape.import(params[:file])
    redirect_to root_url, success: "Tapes Imported"
  end

  def deleted
    @tapes = Tape.only_deleted
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tape
      @tape = Tape.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tape_params
      params.require(:tape).permit(:reference, :customer_id)
    end
end

app/helpers/tapes_helper.rb
module TapesHelper
end

app/views/tapes/_edit_form.html.haml
=form_for @tape do |f|
  %div.field
    =f.label :reference
    =f.text_field :reference

  %div.field
    =f.label :customer_id
    -customer_hash = Hash.new(0)
    -@customers.each do |customer|
      -customer_hash[customer.name] = customer.id
    =f.select(:customer_id, customer_hash)

  %div.field
    =f.label :location
    -location_hash = Hash.new(0)
    -@locations.each do |location|
      -location_hash[location.location] = location.id
    =f.select :location, location_hash, :selected => @tape.location.id

  %div.actions
    =f.submit

app/views/tapes/_form.html.haml
=form_for(@tape, :html => { :class => 'form-horizontal', :role => 'form', :onsubmit => 'return validateTapeForm()' }) do |f|
  -if @tape.errors.any?
    %div#error_explanation
      %h2= #{pluralize(@tape.errors.count, "error")} prohibited this tape from being saved:
      =debug(@tapes)
      %ul
        -@tape.errors.full_messages.each do |msg|
          %li= msg

  %div.form-group
    %div.col-sm-10
      =f.label :reference
      =text_field_tag(:reference, '', :class => 'form-control')

  %div.form-group
    %div.col-sm-10
      =f.select :reference, options_for_select([]), {}, {:class => 'form-control', :multiple => true}

  %div.form-group
    %div.col-sm-10
      =link_to 'Remove Tape', '#', :class => 'btn btn-mini btn-danger', :id => 'remove_tape'

  %br

  %div.form-group
    %div.col-sm-10
      =f.label :customer_id
      -customer_hash = Hash.new(0)
      -@customers.each do |customer|
        -customer_hash[customer.name] = customer.id
      =f.select(:customer_id, customer_hash, {}, :class => 'form-control')

  %div.form-group
    %div.col-sm-10
      =f.submit :class => 'btn btn-primary'

%h2 Import Tapes From CSV
=form_tag import_tapes_path, multipart: true do
  =file_field_tag :file, :class => 'form-control'
  %br
  =submit_tag "Import", :class => 'btn btn-primary'
  %br

app/views/tapes/deleted.html.haml
%h1 Deleted Tapes

%table.table.table-striped
  %thead
    %tr
      %th Tape ref
      %th Location
      %th Customer
      %th Deleted At
      %th Deleted By

  %tbody
    -@tapes.each do |tape|
      %tr
        %td= tape.reference
        %td= tape.location.location
        %td= tape.customer.name
        %td= tape.deleted_at
        %td= tape.deleted_by

app/views/tapes/edit.html.erb
<h1>Editing tape</h1>

<%= render 'edit_form' %>

<%= link_to 'Show', @tape %> |
<%= link_to 'Back', tapes_path %>

app/views/tapes/import.html.haml
%h1 Import Tapes

=render 'import_form'

=link_to 'Back', tapes_path 

app/views/tapes/index.html.haml
%h1 Tape Locations

= form_tag tapes_path, :method => 'get', :id => "tapes_search" do
  %p
  %div
    = text_field_tag :search, params[:search], class: 'span2 search-query'
    = submit_tag "Search", :name => nil, class: 'btn'
    %br
    %br


%table.table.table-striped
  %thead
    %tr
      %th Tape ref
      %th Location
      %th Customer
      %th History
      %th Edit
      %th Delete

  %tbody
    -@tapes.each do |tape|
      %tr
        %td= tape.reference
        %td= tape.location.location
        %td= tape.customer.name
        %td= link_to "Tape History", "/tapes/#{tape.id}/history"
        %td= link_to 'Edit', edit_tape_path(tape)
        %td= link_to 'Destroy', tape, method: :delete, data: { confirm: 'Are you sure?' }

%br
=will_paginate @tapes
%br
=link_to 'New Tape', new_tape_path, :class => 'btn btn-primary'

app/views/tapes/new.html.haml
%h1 New tapes
  
=render 'form'

=link_to 'Back', tapes_path

app/views/tapes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tape ref:</strong>
  <%= @tape.reference %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @tape.customer_id %>
</p>

<%= link_to 'Edit', edit_tape_path(@tape) %> |
<%= link_to 'Back', tapes_path %>