config/routes.rb
BarcodeScanner::Application.routes.draw do
  mount Judge::Engine => '/judge'
  devise_for :users
  resources :locations

  resources :customers

  resources :tapes do
    resources :history, controller: 'history'
    collection { post :import }
    collection { get  :deleted }
  end

  resources :customers do
    resources :history, controller: 'audits'
    collection { post :import }
    collection { get  :deleted }
  end

  resources :consignments do
    collection do
      get 'checktape'
    end
  end

  root 'tapes#index'

end

app/views/layouts/application.html.haml
!!!
%html
	%head
		%title LUK Media Handling
		= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
		= javascript_include_tag "application", "data-turbolinks-track" => true
		= csrf_meta_tags
		= favicon_link_tag

	%body
		= nav_bar :fixed => :top, :brand => "LUK Media Handling", :brand_link => root_path do
			-if current_user
				=menu_group do
					=drop_down "Tapes" do
						= menu_item "View all", root_path
						= menu_item "Deleted Tapes", deleted_tapes_path
						= menu_item "Add Tapes", new_tape_path
					=drop_down "Consignments" do
						= menu_item "View all", consignments_path
						= menu_item "Create new", new_consignment_path
					= menu_item "Customers", customers_path
					= menu_item "Locations", locations_path
				= menu_group :pull => :right do
					= drop_down current_user.email do
						= menu_item "log out", destroy_user_session_path, :method => :delete

		%div.container-fluid
			= yield